### ISSUE TITLE
Design and implement tile to show vehicle identifier number in vehicle properties area

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2022ws02-automotive-test-app#110]
## User story
1. As a user
2. I want to be able to see the vehicle identifier number in the vehicle properties context
3. So that I can identify my car.

## Acceptance criteria
* In the vehicle properties context area, there is a new tile for the vehicle identifier number.
* The tile has a title.
* On the tile, the vehicle identifier number of the car is shown.

## Definition of done (DoD)
* Code compiles and builds 
* Acceptance criteria are met
* Tests have been written and were passed 
* Code is peer-reviewed 
* Feature is merged into development branch
* Documentation is updated 
* Bill of Materials is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by LaraSlzb** [comment]
I could not read the official vin because the property INFO_VIN needs the PERMISSION_IDENTIFICATION which is protected by "signature|privileged" protection level. So this is only possible for system apps. In the meeting on Friday we decided to make the vin editable. Now it is possible to enter the vin of the car into the app and save it for later use.
